### PR TITLE
Dood Scratch Test and Igloo Toggle in Hardware

### PR DESCRIPTION
**Pull request by caleb-james-smith**
Dood Request for you!
Scratch test for Bridge now writes dood = 100 111 111 100
Hardware contains Igloo Toggle

### CODE REVIEW

**Comment by caleb-james-smith** [comment]
~~ Begin Toggle Igloo Power Slave
Igloo Control = 0 0 7 224
Igloo Ones = 255 255 255 255
Igloo Control = 0 0 3 224
Igloo Power Off Confirmed.
Igloo Ones = 1 0 0 0 0
Igloo Control = 0 0 7 224
Igloo Ones = 255 255 255 255
~~ Toggle Igloo Power PASS
True
~~ Begin Toggle Igloo Power Slave
Igloo Control = 0 0 7 224
Igloo Ones = 255 255 255 255
Igloo Control = 0 0 3 224
Igloo Power Off Confirmed.
Igloo Ones = 1 0 0 0 0
Igloo Control = 0 0 7 224
Igloo Ones = 255 255 255 255
~~ Toggle Igloo Power PASS
True
~~ Begin Toggle Igloo Power Slave
Igloo Control = 0 0 7 224
Igloo Ones = 255 255 255 255
Igloo Control = 0 0 3 224
Igloo Power Off Confirmed.
Igloo Ones = 1 0 0 0 0
Igloo Control = 0 0 7 224
Igloo Ones = 255 255 255 255
~~ Toggle Igloo Power PASS
True
~~ Begin Toggle Igloo Power Slave
Igloo Control = 0 0 7 224
Igloo Ones = 255 255 255 255
Igloo Control = 0 0 3 224
Igloo Power Off Confirmed.
Igloo Ones = 1 0 0 0 0
Igloo Control = 0 0 7 224
Igloo Ones = 255 255 255 255
~~ Toggle Igloo Power PASS
True

**Comment by caleb-james-smith** [comment]
2016/07/14 10:56:14 J=24	ID_string_cont tests completed.
2016/07/14 10:56:14 J=24	Initial Read = 0 100 111 111 100
2016/07/14 10:56:14 J=24	Final Read = 0 100 111 111 100
2016/07/14 10:56:14 J=24	Scratch dood success!
2016/07/14 10:56:14 J=24	Initial Read = 0 100 111 111 100
2016/07/14 10:56:14 J=24	Final Read = 0 100 111 111 100
2016/07/14 10:56:14 J=24	Scratch dood success!
2016/07/14 10:56:14 J=24	Initial Read = 0 100 111 111 100
2016/07/14 10:56:14 J=24	Final Read = 0 100 111 111 100
2016/07/14 10:56:14 J=24	Scratch dood success!
2016/07/14 10:56:14 J=24	Initial Read = 0 100 111 111 100
2016/07/14 10:56:14 J=24	Final Read = 0 100 111 111 100
2016/07/14 10:56:14 J=24	Scratch dood success!
2016/07/14 10:56:14 J=24	Initial Read = 0 100 111 111 100
2016/07/14 10:56:14 J=24	Final Read = 0 100 111 111 100
2016/07/14 10:56:14 J=24	Scratch dood success!
2016/07/14 10:56:14 J=24	Initial Read = 0 100 111 111 100
2016/07/14 10:56:14 J=24	Final Read = 0 100 111 111 100
2016/07/14 10:56:14 J=24	Scratch dood success!
2016/07/14 10:56:14 J=24	Initial Read = 0 100 111 111 100
2016/07/14 10:56:14 J=24	Final Read = 0 100 111 111 100
2016/07/14 10:56:14 J=24	Scratch dood success!
2016/07/14 10:56:14 J=24	Initial Read = 0 100 111 111 100
2016/07/14 10:56:14 J=24	Final Read = 0 100 111 111 100
2016/07/14 10:56:14 J=24	Scratch dood success!
2016/07/14 10:56:14 J=24	Initial Read = 0 100 111 111 100
2016/07/14 10:56:14 J=24	Final Read = 0 100 111 111 100
2016/07/14 10:56:14 J=24	Scratch dood success!
2016/07/14 10:56:14 J=24	Initial Read = 0 100 111 111 100
2016/07/14 10:56:14 J=24	Final Read = 0 100 111 111 100
2016/07/14 10:56:14 J=24	Scratch dood success!
2016/07/14 10:56:14 J=24	Initial Read = 0 100 111 111 100
2016/07/14 10:56:14 J=24	Final Read = 0 100 111 111 100
2016/07/14 10:56:14 J=24	Scratch dood success!
2016/07/14 10:56:14 J=24	Initial Read = 0 100 111 111 100
2016/07/14 10:56:14 J=24	Final Read = 0 100 111 111 100
2016/07/14 10:56:14 J=24	Scratch dood success!
2016/07/14 10:56:14 J=24	Initial Read = 0 100 111 111 100
2016/07/14 10:56:14 J=24	Final Read = 0 100 111 111 100
2016/07/14 10:56:14 J=24	Scratch dood success!
2016/07/14 10:56:14 J=24	Initial Read = 0 100 111 111 100
2016/07/14 10:56:14 J=24	Final Read = 0 100 111 111 100
2016/07/14 10:56:14 J=24	Scratch dood success!
2016/07/14 10:56:14 J=24	Initial Read = 0 100 111 111 100
2016/07/14 10:56:14 J=24	Final Read = 0 100 111 111 100
2016/07/14 10:56:14 J=24	Scratch dood success!
2016/07/14 10:56:14 J=24	Initial Read = 0 100 111 111 100
2016/07/14 10:56:14 J=24	Final Read = 0 100 111 111 100
2016/07/14 10:56:14 J=24	Scratch dood success!
2016/07/14 10:56:14 J=24	Initial Read = 0 100 111 111 100
2016/07/14 10:56:14 J=24	Final Read = 0 100 111 111 100
2016/07/14 10:56:14 J=24	Scratch dood success!
2016/07/14 10:56:14 J=24	Initial Read = 0 100 111 111 100
2016/07/14 10:56:14 J=24	Final Read = 0 100 111 111 100
2016/07/14 10:56:14 J=24	Scratch dood success!
2016/07/14 10:56:14 J=24	Initial Read = 0 100 111 111 100
2016/07/14 10:56:14 J=24	Final Read = 0 100 111 111 100
2016/07/14 10:56:14 J=24	Scratch dood success!
2016/07/14 10:56:14 J=24	Initial Read = 0 100 111 111 100
2016/07/14 10:56:14 J=24	Final Read = 0 100 111 111 100
2016/07/14 10:56:14 J=24	Scratch dood success!
2016/07/14 10:56:14 J=24	Scratch tests completed.

**Comment by caleb-james-smith** [comment]
Updated output after merge:

~~ Begin Toggle Igloo Power Slave
Igloo Control = 0 0 7 224
Igloo Ones = 255 255 255 255
Igloo Control = 0 0 3 224
Igloo Power Off Confirmed.
Igloo Ones = 1 0 0 0 0
Igloo Control = 0 0 7 224
Igloo Ones = 255 255 255 255
~~ Toggle Igloo Power PASS
True
~~ Begin Toggle Igloo Power Slave
Igloo Control = 0 0 7 224
Igloo Ones = 255 255 255 255
Igloo Control = 0 0 3 224
Igloo Power Off Confirmed.
Igloo Ones = 1 0 0 0 0
Igloo Control = 0 0 7 224
Igloo Ones = 255 255 255 255
~~ Toggle Igloo Power PASS
True
~~ Begin Toggle Igloo Power Slave
Igloo Control = 0 0 7 224
Igloo Ones = 255 255 255 255
Igloo Control = 0 0 3 224
Igloo Power Off Confirmed.
Igloo Ones = 1 0 0 0 0
Igloo Control = 0 0 7 224
Igloo Ones = 255 255 255 255
~~ Toggle Igloo Power PASS
True
~~ Begin Toggle Igloo Power Slave
Igloo Control = 0 0 7 224
Igloo Ones = 255 255 255 255
Igloo Control = 0 0 3 224
Igloo Power Off Confirmed.
Igloo Ones = 1 0 0 0 0
Igloo Control = 0 0 7 224
Igloo Ones = 255 255 255 255
~~ Toggle Igloo Power PASS
True

**Comment by caleb-james-smith** [comment]
Updated Output after merge:

2016/07/14 11:15:05 J=07	Initial Read = 0 100 111 111 100
2016/07/14 11:15:05 J=07	Final Read = 0 100 111 111 100
2016/07/14 11:15:05 J=07	Scratch dood success!
2016/07/14 11:15:05 J=07	Initial Read = 0 100 111 111 100
2016/07/14 11:15:05 J=07	Final Read = 0 100 111 111 100
2016/07/14 11:15:05 J=07	Scratch dood success!
2016/07/14 11:15:05 J=07	Initial Read = 0 100 111 111 100
2016/07/14 11:15:05 J=07	Final Read = 0 100 111 111 100
2016/07/14 11:15:05 J=07	Scratch dood success!
2016/07/14 11:15:05 J=07	Initial Read = 0 100 111 111 100
2016/07/14 11:15:05 J=07	Final Read = 0 100 111 111 100
2016/07/14 11:15:05 J=07	Scratch dood success!
2016/07/14 11:15:05 J=07	Initial Read = 0 100 111 111 100
2016/07/14 11:15:05 J=07	Final Read = 0 100 111 111 100
2016/07/14 11:15:05 J=07	Scratch dood success!
2016/07/14 11:15:05 J=07	Initial Read = 0 100 111 111 100
2016/07/14 11:15:05 J=07	Final Read = 0 100 111 111 100
2016/07/14 11:15:05 J=07	Scratch dood success!
2016/07/14 11:15:05 J=07	Initial Read = 0 100 111 111 100
2016/07/14 11:15:05 J=07	Final Read = 0 100 111 111 100
2016/07/14 11:15:05 J=07	Scratch dood success!
2016/07/14 11:15:05 J=07	Initial Read = 0 100 111 111 100
2016/07/14 11:15:05 J=07	Final Read = 0 100 111 111 100
2016/07/14 11:15:05 J=07	Scratch dood success!
2016/07/14 11:15:05 J=07	Initial Read = 0 100 111 111 100
2016/07/14 11:15:05 J=07	Final Read = 0 100 111 111 100
2016/07/14 11:15:05 J=07	Scratch dood success!
2016/07/14 11:15:05 J=07	Initial Read = 0 100 111 111 100
2016/07/14 11:15:05 J=07	Final Read = 0 100 111 111 100
2016/07/14 11:15:05 J=07	Scratch dood success!
2016/07/14 11:15:05 J=07	Initial Read = 0 100 111 111 100
2016/07/14 11:15:05 J=07	Final Read = 0 100 111 111 100
2016/07/14 11:15:05 J=07	Scratch dood success!
2016/07/14 11:15:05 J=07	Initial Read = 0 100 111 111 100
2016/07/14 11:15:05 J=07	Final Read = 0 100 111 111 100
2016/07/14 11:15:05 J=07	Scratch dood success!
2016/07/14 11:15:05 J=07	Initial Read = 0 100 111 111 100
2016/07/14 11:15:05 J=07	Final Read = 0 100 111 111 100
2016/07/14 11:15:05 J=07	Scratch dood success!
2016/07/14 11:15:05 J=07	Initial Read = 0 100 111 111 100
2016/07/14 11:15:05 J=07	Final Read = 0 100 111 111 100
2016/07/14 11:15:05 J=07	Scratch dood success!
2016/07/14 11:15:05 J=07	Initial Read = 0 100 111 111 100
2016/07/14 11:15:05 J=07	Final Read = 0 100 111 111 100
2016/07/14 11:15:05 J=07	Scratch dood success!
2016/07/14 11:15:05 J=07	Initial Read = 0 100 111 111 100
2016/07/14 11:15:05 J=07	Final Read = 0 100 111 111 100
2016/07/14 11:15:05 J=07	Scratch dood success!
2016/07/14 11:15:05 J=07	Initial Read = 0 100 111 111 100
2016/07/14 11:15:05 J=07	Final Read = 0 100 111 111 100
2016/07/14 11:15:05 J=07	Scratch dood success!
2016/07/14 11:15:05 J=07	Initial Read = 0 100 111 111 100
2016/07/14 11:15:05 J=07	Final Read = 0 100 111 111 100
2016/07/14 11:15:05 J=07	Scratch dood success!
2016/07/14 11:15:05 J=07	Initial Read = 0 100 111 111 100
2016/07/14 11:15:05 J=07	Final Read = 0 100 111 111 100
2016/07/14 11:15:05 J=07	Scratch dood success!
2016/07/14 11:15:05 J=07	Initial Read = 0 100 111 111 100
2016/07/14 11:15:05 J=07	Final Read = 0 100 111 111 100
2016/07/14 11:15:05 J=07	Scratch dood success!
2016/07/14 11:15:05 J=07	Scratch tests completed.

**Comment by potarf** [comment]
Great!

**Pull request merged**
