### PR TITLE
iglooClass_adry.py, IglooLib_adry.py

### PR DESCRIPTION
**Pull request by adrysmith**
Changes made in the _adry version of the iglooClass and IglooLib, so they'll have to be placed into the test suite at Shaun's discretion. 

I have updated the 5 'counter' tests in iglooClass_adry.py. They are called:
1. clk_count (ensures the clock is increasing at 40MHz)
2. rst_QIE_count (ensures increase of 11kHz)
3. wte_count (ensures increases of ~37kHz... This value may need to be 11kHz also, but this cut matches the data currently)
4. capIDErr_count (tests both CapIdErrLink1_count and CapIdErrLink2_count... ensures that the register can be read from... After igloo firmware fixes, hopefully we can make sure this reads 'zero' errors)

I also do "import helpers" and "import time" at the top of the igloo class now.

In IglooLib_adry.py, I've written a new function called intListToString that I use for the modified tests above.

These functions have been tested and work as expected.

### CODE REVIEW

**Comment by adrysmith** [comment]
If other files/commits look like they've happened since my last pull request, part of those may come from me utterly changing large swaths of some other files to accommodate pulling from baylor master. I mostly just deleted my old version of certain code to get up to date.

**Comment by caleb-james-smith** [comment]
Awesome, those will be useful tests. I also want to ask Joe about our
Firmware tests... I think we want to read the Firmware. :) We do read the
Firmware in the Preliminary Test Stand, but this would confirm the value.

**Comment by pastika** [comment]
If we can add a check of the fw to station 2 in very short I say go for it.

Cheers,
Joe

**Comment by potarf** [comment]
Good, thank you!

**Pull request merged**
