### PR TITLE
A Recipe for Progress

### PR DESCRIPTION
**Pull request by shaunhogan**
This recipe has been a long-standing favorite of mine. My mother used to make this for me as a child, and every time I cook this up nowadays, the scents just bring me back to my youth. Without further delay:

**INGREDIENTS**
- One part fixing a uHTR test that crashed testing after a particularly bad mapping.
- One part each of updating the list of tests to run, along with the list of test outputs in the JSON file
- Three parts of changing igloo tests
- Four parts of fixing the resulting merge conflicts and other issues within the code (_**This is important!**_)

**PROCEDURE**
-  Randomly mix ingredients together and if you're lucky, everything will work.

Stable.

### CODE REVIEW

**Comment by potarf** [comment]
"PROCEDURE

Randomly mix ingredients together and if you're lucky, everything will work.
Stable." this seems a bit worrisome

**Comment by caleb-james-smith** [comment]
Sounds quite tasty, sir! Just bring it over and we will cook it for dinner.

**Comment by shaunhogan** [comment]
I liken it to throwing random foodstuffs into a blender. Sometimes you'll get a strawberry smoothie, but other times you'll get basil-sauerkraut puree.

**Comment by shaunhogan** [comment]
That doesn't help my case.

**Comment by caleb-james-smith** [comment]
I wonder if we just want to use percent error for all "Counter" tests.

**Comment by shaunhogan** [comment]
Ah. I like having a percent error counter a lot more. Gives us more variation in how long tests run.

**Comment by caleb-james-smith** [comment]
Yes, we can play with the cutoff... I am not sure how exact each counter will be once we test them.

**Comment by shaunhogan** [comment]
Anyways, @potarf , this has been tested to work, and I think Mason was waiting for this to get uploaded so that he can modify the uHTR.py file while including my changes. The counter tests work for now, but that's something to add to the to-do list.

**Comment by potarf** [comment]
Thanks! Sorry for the confusion!

**Pull request merged**
