### PR TITLE
OpenRM channels, Temperature and Humidity, Checksums

### PR DESCRIPTION
**Pull request by caleb-james-smith**
If you are feeling crazy, here are some commits. Good luck!

### CODE REVIEW

**Comment by potarf** [comment]
Please remove all logs and json files from this pull request

**Comment by potarf** [comment]
Also, needs to pull changes which delete files in client directory

**Comment by caleb-james-smith** [comment]
Is this my old pull request? I can look at it. I should try to get up to date. My last attempt in pulling from Shaun was not updating my local repository for some reason... this was a feed days ago, though.

Caleb

"The things which you have heard from me in the presence of many witnesses, entrust these to faithful men, who will be able to teach others also." 2 Timothy 2:2

**Comment by potarf** [comment]
Pull requests continually update with your latest on the master, so if you make the changes to your master branch, they show up here. All pull requests are as recent as the submitter's latest changes!

**Comment by potarf** [comment]
Looks good :)

**Pull request merged**
